<Project>
  <Target Name="AttachPackageReadmeAndIcon" BeforeTargets="Pack">
    <!-- Pack README.md into the NuGet package root if it exists -->
    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath="" Condition="Exists('README.md')" />
    </ItemGroup>
  </Target>
  
  <PropertyGroup Condition="'$(IsTestProject)'=='true'">
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
