// Copyright (c) KeelMatrix

using System.Text;
using FluentAssertions;

namespace KeelMatrix.Telemetry.UnitTests.Style {
    public sealed class SourceHeaderTests {
        private const string CopyrightHeaderText = "// Copyright (c) KeelMatrix";

        [Fact]
        public void All_Cs_Files_Must_Have_Correct_Copyright_Header() {
            // Locate solution root by walking upward from test assembly
            var baseDir = AppContext.BaseDirectory;
            var dir = new DirectoryInfo(baseDir);

            while (dir?.EnumerateFiles("*.slnx").Any() == false) {
                dir = dir.Parent;
            }

            dir.Should().NotBeNull("test must be executed within a solution directory structure");
            var solutionRoot = dir!.FullName;

            // Find all .cs files under solution, excluding bin/obj cross-platform
            var csFiles = Directory.EnumerateFiles(solutionRoot, "*.cs", SearchOption.AllDirectories)
                .Where(p => !IsInBuildFolder(p))
                .ToList();

            csFiles.Should().NotBeEmpty("solution should contain C# source files");
            var offenders = new List<string>();

            foreach (string file in csFiles) {
                var lines = File.ReadAllLines(file, Encoding.UTF8);

                if (lines.Length < 2 ||
                    (lines[0] != "// <auto-generated/>" &&
                     (lines[0] != CopyrightHeaderText || lines[1].Length != 0))) {
                    offenders.Add(Path.GetRelativePath(solutionRoot, file));
                }
            }

            offenders.Should().BeEmpty(
                "All .cs files must begin with the copyright header followed by exactly one empty line"
            );
        }

        private static bool IsInBuildFolder(string path) {
            char[] separators = [Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar];
            string[] segments = path.Split(separators, StringSplitOptions.None);
            return segments.Any(s =>
                s.Equals("bin", StringComparison.OrdinalIgnoreCase) ||
                s.Equals("obj", StringComparison.OrdinalIgnoreCase));
        }
    }
}
